%{
To show example trace, data from ['DATA_',filename,'.mat'] generated by "Code_FIcurve_extract"

%}
%%
clear all;clc

Fidx{1}=dir('DATA_*L2PC_FIcurve.mat');
Fidx{2}=dir('DATA_*L5PC_FIcurve.mat');

colorma=[1,0,0
    0,1,0];


AmpWant=[50,100,300,1000,2000];

%%

for kk=1:length(Fidx)
    for k=1:length(Fidx{kk})
        
        clearvars -except AmpWant FreqWant colorma Fidx kk  k
        
        filename=Fidx{kk}(k).name;
        load(filename)
        disp([num2str(k),'/',num2str(length(Fidx{kk})),'--',num2str(kk),'/',num2str(length(Fidx)),'--',filename])
        %%
        
        for i=1:length(AmpWant)
            idx=find(abs(StimAmp-AmpWant(i))==min(abs(StimAmp==AmpWant(i))),1,'first');
            
            if ~isempty(idx)%& mean(spkFreq(idx))>=FreqWant(i,1)&mean(spkFreq(idx))<=FreqWant(i,2)
                
                figure(1)
                subplot(length(Fidx),length(AmpWant),i+(kk-1)*length(AmpWant));
                plot(tspanV,waveformV(:,idx),'color',colorma(kk,:),'Displayname',num2str(mean(spkFreq(idx)))),hold on
                title([num2str(mean(spkFreq(idx))),' Hz'])
                axis([tspanV(1),tspanV(end),-80,50])
                %                 axis off
                
                drawnow
                
            end
            
        end
        
    end
end



% (c) 2018 He quansheng
% State Key Laboratory of Cognitive Neuroscience and Learning & IDG/McGovern 
% Institute for Brain Research, Beijing Normal University
% quanshe@mail.bnu.edu.cn