% To analyze ['DATA_',filename,'.mat'] generated by "Code_FIcurve_extract"
%
% Quansheng
% quanshe@mail.bnu.edu.cn
%
%% 
clear all;clc

Fidx{1}=dir('DATA_*L2PC_FIcurve.mat');
Fidx{2}=dir('DATA_*L5PC_FIcurve.mat');

colorma=[1,0,0
    0,1,0];

Binwidth=50;
BinL=0:Binwidth:200-Binwidth;
BinR=BinL+Binwidth;
BinsFIcurveS=[BinL',BinR'];

Binwidth=100;
BinL=200:Binwidth:2500-Binwidth;
BinR=BinL+Binwidth;
BinsFIcurveL=[BinL',BinR'];

BinsFIcurve{1}=[BinsFIcurveS;BinsFIcurveL];
BinsFIcurve{2}=[BinsFIcurveS;BinsFIcurveL];


Name={'L2PC','L5PC'};

%%

for kk=1:length(Fidx)
    for k=1:length(Fidx{kk})
        filename=Fidx{kk}(k).name;
        load(filename)
        disp([num2str(k),'/',num2str(length(Fidx{kk})),'--',num2str(kk),'/',num2str(length(Fidx)),'--',filename])
        %% ------------- fitting ReLU function ---------------------------
        Fun=@(a,b,x) max([zeros(length(x),1),a.*x(:)+b],[],2);
        fo= fitoptions('Method','NonlinearLeastSquares',...
            'Lower',[0.001,-1000],...
            'Upper',[10,1000], ...
            'Startpoint',[0.1,-10]);
        
        [tempx,idx]=sort(StimAmp);tempy=spkFreq(idx);
        idx=find(tempy>=20,1,'first');
        x=[0,tempx(1:idx)];
        y=[0;tempy(1:idx)];
        
        [Model,~]=fit(x(:),y(:),fittype(Fun));
        beta=coeffvalues(Model);
        xx=linspace(0,x(end),100);
        yy=feval(Model,xx);
        
        figure(1),clf
        plot(StimAmp,spkFreq,'ro','markerfacecolor',colorma(kk,:)),hold on
        plot(xx,yy,'r')
        drawnow
        
        FIcurveParamRecord{kk}(k,:)=abs(beta);
        %% ------------- Bin FIcurve ---------------------------
        
        for i=1:size(BinsFIcurve{kk},1)
            idx=StimAmp>BinsFIcurve{kk}(i,1)&StimAmp<=BinsFIcurve{kk}(i,2);
            if ~isempty(idx)
                spkFreqBin{kk}(k,i)=mean(spkFreq(idx));
            else
                spkFreqBin{kk}(k,i)=nan;
            end
            
        end
        
        %% ------------- Bin spkshape,1~5 AP first spike ---------------------------
        Binwidth=5;
        BinL=2:Binwidth:50-Binwidth;
        BinR=BinL+Binwidth;
        BinsSpkshape=[BinL',BinR'];
        
        for i=1:size(BinsSpkshape,1)
            idx=find(spkFreq>BinsSpkshape(i,1)&spkFreq<=BinsSpkshape(i,2),1,'first');
            
            if ~isempty(idx)
                [spkwaveform,ttspan,HW, AHP, Threshold, Amp,HWidx,AHPidx, Thresholdidx, spktime] = AP_Statistic(waveformV(:,idx),tspanV,1);
                
                spkwaveformRecord{kk}(k,:,i) =spkwaveform(:);
                HWRecord{kk}(k,i)=HW;
                AHPRecord{kk}(k,i)=AHP;
                ThresholdRecord{kk}(k,i)=Threshold;
                AmpRecord{kk}(k,i)=Amp;
                
                figure(3),clf
                plot(ttspan,spkwaveform,'color',colorma(kk,:)),hold on
                plot(ttspan(HWidx),spkwaveform(HWidx),'mo')
                plot(ttspan(AHPidx),spkwaveform(AHPidx),'go')
                plot(ttspan(Thresholdidx),spkwaveform(Thresholdidx),'ms')
                drawnow
            else
                spkwaveformRecord{kk}(k,:,i) =nan(length(ttspan),1);
                HWRecord{kk}(k,i)=nan;
                AHPRecord{kk}(k,i)=nan;
                ThresholdRecord{kk}(k,i)=nan;
                AmpRecord{kk}(k,i)=nan;
            end
            
        end
        
    end
end

save('Results_FIcurve.mat','Fidx','Name','colorma',...
    'spkwaveformRecord','HWRecord','AHPRecord','ThresholdRecord','AmpRecord','ttspan','BinsSpkshape',...
    'spkFreqBin','BinsFIcurve','FIcurveParamRecord')

%% To export Results into Excel file (not recommend)
for kk=1:length(Fidx)
    % ------
    xlswrite('Results_FIcurve.xls',mean(BinsSpkshape,2)',['HW_',Name{kk}],'A1')
    xlswrite('Results_FIcurve.xls',HWRecord{kk},['HW_',Name{kk}],'A2')
    xlswrite('Results_FIcurve.xls',mean(BinsSpkshape,2)',['AHP_',Name{kk}],'A1')
    xlswrite('Results_FIcurve.xls',AHPRecord{kk},['AHP_',Name{kk}],'A2')
    xlswrite('Results_FIcurve.xls',mean(BinsSpkshape,2)',['threshold_',Name{kk}],'A1')
    xlswrite('Results_FIcurve.xls',ThresholdRecord{kk},['threshold_',Name{kk}],'A2')
    xlswrite('Results_FIcurve.xls',mean(BinsSpkshape,2)',['Amp_',Name{kk}],'A1')
    xlswrite('Results_FIcurve.xls',AmpRecord{kk},['Amp_',Name{kk}],'A2')
    
    % ------
    xlswrite('Results_FIcurve.xls',mean(BinsFIcurve{kk},2)',['FIcurve_',Name{kk}],'A1')
    xlswrite('Results_FIcurve.xls',spkFreqBin{kk},['FIcurve_',Name{kk}],'A2')
    
    % ------
    xlswrite('Results_FIcurve.xls',{'slope','onset'},['FIcurve_ReLU_',Name{kk}],'A1')
    xlswrite('Results_FIcurve.xls',FIcurveParamRecord{kk},['FIcurve_ReLU_',Name{kk}],'A2')
    
end

%%

clear all;
load('Results_FIcurve.mat')

% ==================== FIcurve ====================
figure(1),clf

for kk=1:length(Fidx)
    x=mean(BinsFIcurve{kk},2);
    y=nanmean(spkFreqBin{kk},1);
    N=sum(~isnan(spkFreqBin{kk}),1);
    sem=nanstd(spkFreqBin{kk},[],1)./sqrt(N);
    
    errorbar(x,y,sem,'-o','color',colorma(kk,:),'markerfacecolor',colorma(kk,:),'markersize',8),hold on
    
end
legend(Name)
ylabel('Frequency (Hz)')
xlabel('Current injection (pA)')

% for i=1:size(spkFreqBin{1},2)
%     if ~isnan([spkFreqBin{1}(:,i);spkFreqBin{2}(:,i)])
%         [~,p]=ttest2(spkFreqBin{1}(:,i),spkFreqBin{2}(:,i));
%
%         if p<0.05;
%             text(x(i),y(i),num2str(p));
%         end
%     end
% end

% ==================== ReLU statistic ====================
figure(2),clf
% [~,p1]=ttest2(FIcurveParamRecord{1}(:,1),FIcurveParamRecord{2}(:,1));
% [~,p2]=ttest2(FIcurveParamRecord{1}(:,2),FIcurveParamRecord{2}(:,2));

for kk=1:length(Fidx)
    subplot(211)
    bar(kk,nanmean(FIcurveParamRecord{kk}(:,1)),'facecolor',colorma(kk,:)),hold on
    errorbar(kk,nanmean(FIcurveParamRecord{kk}(:,1)),nanstd(FIcurveParamRecord{kk}(:,1))./sqrt(size(FIcurveParamRecord{kk}(:,1),1)),'color',colorma(kk,:))
    %     title(['p = ',num2str(p1)])
    ylabel('FIcurve slope')
    
    subplot(212)
    bar(kk,nanmean(FIcurveParamRecord{kk}(:,2)),'facecolor',colorma(kk,:)),hold on
    errorbar(kk,nanmean(FIcurveParamRecord{kk}(:,2)),nanstd(FIcurveParamRecord{kk}(:,2))./sqrt(size(FIcurveParamRecord{kk}(:,2),1)),'color',colorma(kk,:))
    %     title(['p = ',num2str(p2)])
    ylabel('FIcurve threshold')
end

% ==================== spkshape statistic ====================
figure(3),clf
for kk=1:length(Fidx)
    subplot(1,4,1)
    N=sum(~isnan(HWRecord{kk}));
    errorbar(mean(BinsSpkshape,2),nanmean(HWRecord{kk},1),nanstd(HWRecord{kk},[],1)./sqrt(N),'-o','color',colorma(kk,:),'markerfacecolor',colorma(kk,:)),hold on
    title('HW')
    
    subplot(1,4,2)
    N=sum(~isnan(AHPRecord{kk}));
    errorbar(mean(BinsSpkshape,2),nanmean(AHPRecord{kk},1),nanstd(AHPRecord{kk},[],1)./sqrt(N),'-o','color',colorma(kk,:),'markerfacecolor',colorma(kk,:)),hold on
    title('AHP')
    
    subplot(1,4,3)
    N=sum(~isnan(ThresholdRecord{kk}));
    errorbar(mean(BinsSpkshape,2),nanmean(ThresholdRecord{kk},1),nanstd(ThresholdRecord{kk},[],1)./sqrt(N),'-o','color',colorma(kk,:),'markerfacecolor',colorma(kk,:)),hold on
    title('Threshold')
    
    subplot(1,4,4)
    N=sum(~isnan(AmpRecord{kk}));
    errorbar(mean(BinsSpkshape,2),nanmean(AmpRecord{kk},1),nanstd(AmpRecord{kk},[],1)./sqrt(N),'-o','color',colorma(kk,:),'markerfacecolor',colorma(kk,:)),hold on
    title('Amp')
    xlabel('Frequency (Hz)')
end
legend(Name)

% for i=1:size(HWRecord{1},2)
%     [~,pHW]=ttest2(HWRecord{1}(:,i),HWRecord{2}(:,i));
%     [~,pTH]=ttest2(ThresholdRecord{1}(:,i),ThresholdRecord{2}(:,i));
%     [~,pAHP]=ttest2(AHPRecord{1}(:,i),AHPRecord{2}(:,i));
%
%     if pHW<0.05;
%         subplot(1,4,1)
%         text(mean(BinsSpkshape(i,:),2),nanmean(HWRecord{kk}(:,i),1),num2str(pHW));
%     end
%
%     if pAHP<0.05;
%          subplot(1,4,2)
%         text(mean(BinsSpkshape(i,:),2),nanmean(AHPRecord{kk}(:,i),1),num2str(pTH));
%     end
%
%     if pTH<0.05;
%          subplot(1,4,3)
%         text(mean(BinsSpkshape(i,:),2),nanmean(ThresholdRecord{kk}(:,i),1),num2str(pAHP));
%     end
%
% end

% ==================== spkshape waveform ====================
figure(4),clf
figure(5),clf
for kk=1:length(Fidx)
    
    idx=[1,size(spkwaveformRecord{kk},3)-3];
    
    HH=[];
    for i=1:length(idx)
        figure(4)
        HH(i)=subplot(1,length(idx),i);
        data=nanmean(spkwaveformRecord{kk}(:,:,idx(i)),1);
        plot(ttspan,data,'color',colorma(kk,:)),hold on
        axis tight
        
        figure(5)
        tempidx=find(ttspan>-0.004&ttspan<0.0020);
        plot(data(tempidx(2:end)),diff(data(tempidx))*100,'color',colorma(kk,:)),hold on
    end
    
end

linkaxes(HH)
